name: activeem
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - pyyaml
  - matplotlib
  - scikit-learn
  - pytorch
  - tqdm
  - pytest
  - pip
  - pip:
      - -e .
